# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples/CMakeFiles /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples/cpp/OpenLicht/CMakeFiles/progress.marks
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f CMakeFiles/Makefile2 cpp/OpenLicht/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f CMakeFiles/Makefile2 cpp/OpenLicht/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f CMakeFiles/Makefile2 cpp/OpenLicht/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f CMakeFiles/Makefile2 cpp/OpenLicht/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
cpp/OpenLicht/CMakeFiles/LibsModule.dir/rule:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f CMakeFiles/Makefile2 cpp/OpenLicht/CMakeFiles/LibsModule.dir/rule
.PHONY : cpp/OpenLicht/CMakeFiles/LibsModule.dir/rule

# Convenience name for target.
LibsModule: cpp/OpenLicht/CMakeFiles/LibsModule.dir/rule

.PHONY : LibsModule

# fast build rule for target.
LibsModule/fast:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/LibsModule.dir/build.make cpp/OpenLicht/CMakeFiles/LibsModule.dir/build
.PHONY : LibsModule/fast

# Convenience name for target.
cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/rule:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f CMakeFiles/Makefile2 cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/rule
.PHONY : cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/rule

# Convenience name for target.
OpenLicht_3d: cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/rule

.PHONY : OpenLicht_3d

# fast build rule for target.
OpenLicht_3d/fast:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build
.PHONY : OpenLicht_3d/fast

BeepSound.o: BeepSound.cpp.o

.PHONY : BeepSound.o

# target to build an object file
BeepSound.cpp.o:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/BeepSound.cpp.o
.PHONY : BeepSound.cpp.o

BeepSound.i: BeepSound.cpp.i

.PHONY : BeepSound.i

# target to preprocess a source file
BeepSound.cpp.i:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/BeepSound.cpp.i
.PHONY : BeepSound.cpp.i

BeepSound.s: BeepSound.cpp.s

.PHONY : BeepSound.s

# target to generate assembly for a file
BeepSound.cpp.s:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/BeepSound.cpp.s
.PHONY : BeepSound.cpp.s

Bluetooth.o: Bluetooth.cpp.o

.PHONY : Bluetooth.o

# target to build an object file
Bluetooth.cpp.o:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/Bluetooth.cpp.o
.PHONY : Bluetooth.cpp.o

Bluetooth.i: Bluetooth.cpp.i

.PHONY : Bluetooth.i

# target to preprocess a source file
Bluetooth.cpp.i:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/Bluetooth.cpp.i
.PHONY : Bluetooth.cpp.i

Bluetooth.s: Bluetooth.cpp.s

.PHONY : Bluetooth.s

# target to generate assembly for a file
Bluetooth.cpp.s:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/Bluetooth.cpp.s
.PHONY : Bluetooth.cpp.s

Bluetooth_server.o: Bluetooth_server.cpp.o

.PHONY : Bluetooth_server.o

# target to build an object file
Bluetooth_server.cpp.o:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/Bluetooth_server.cpp.o
.PHONY : Bluetooth_server.cpp.o

Bluetooth_server.i: Bluetooth_server.cpp.i

.PHONY : Bluetooth_server.i

# target to preprocess a source file
Bluetooth_server.cpp.i:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/Bluetooth_server.cpp.i
.PHONY : Bluetooth_server.cpp.i

Bluetooth_server.s: Bluetooth_server.cpp.s

.PHONY : Bluetooth_server.s

# target to generate assembly for a file
Bluetooth_server.cpp.s:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/Bluetooth_server.cpp.s
.PHONY : Bluetooth_server.cpp.s

OpenLicht_3d.o: OpenLicht_3d.cpp.o

.PHONY : OpenLicht_3d.o

# target to build an object file
OpenLicht_3d.cpp.o:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/LibsModule.dir/build.make cpp/OpenLicht/CMakeFiles/LibsModule.dir/OpenLicht_3d.cpp.o
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/OpenLicht_3d.cpp.o
.PHONY : OpenLicht_3d.cpp.o

OpenLicht_3d.i: OpenLicht_3d.cpp.i

.PHONY : OpenLicht_3d.i

# target to preprocess a source file
OpenLicht_3d.cpp.i:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/LibsModule.dir/build.make cpp/OpenLicht/CMakeFiles/LibsModule.dir/OpenLicht_3d.cpp.i
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/OpenLicht_3d.cpp.i
.PHONY : OpenLicht_3d.cpp.i

OpenLicht_3d.s: OpenLicht_3d.cpp.s

.PHONY : OpenLicht_3d.s

# target to generate assembly for a file
OpenLicht_3d.cpp.s:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/LibsModule.dir/build.make cpp/OpenLicht/CMakeFiles/LibsModule.dir/OpenLicht_3d.cpp.s
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(MAKE) -f cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/build.make cpp/OpenLicht/CMakeFiles/OpenLicht_3d.dir/OpenLicht_3d.cpp.s
.PHONY : OpenLicht_3d.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... LibsModule"
	@echo "... OpenLicht_3d"
	@echo "... BeepSound.o"
	@echo "... BeepSound.i"
	@echo "... BeepSound.s"
	@echo "... Bluetooth.o"
	@echo "... Bluetooth.i"
	@echo "... Bluetooth.s"
	@echo "... Bluetooth_server.o"
	@echo "... Bluetooth_server.i"
	@echo "... Bluetooth_server.s"
	@echo "... OpenLicht_3d.o"
	@echo "... OpenLicht_3d.i"
	@echo "... OpenLicht_3d.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/pi/Downloads/OpenLicht/libroyale-3.17.0.56-LINUX-arm-32Bit/samples && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

